apiVersion: apps/v1
kind: Deployment
metadata:
  name: vss-deploy
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: "demo002.azurecr.io/sqlwebapp:1.16.0"
        ports:
            - name: http
              containerPort: 80
              protocol: TCP
        livenessProbe:
            httpGet:
              path: /
              port: http
        readinessProbe:
            httpGet:
              path: /
              port: http
        resources:
            {}

